# /etc/portage/env/gcc.conf

CC="gcc"
CXX="g++"
AR="gcc-ar"
NM="gcc-nm"
RANLIB="gcc-ranlib"

BASE_FLAGS_GCC="-O3 -march=native -pipe -fstack-protector-strong"
CFLAGS="${BASE_FLAGS_GCC} -flto=auto"
CXXFLAGS="${BASE_FLAGS_GCC} -flto=auto"

LDFLAGS="-Wl,-O2 -Wl,--as-needed"
