# /etc/portage/env/llvm-kernel.conf
export LLVM=1
export LLVM_IAS=1
CC="clang"
LD="ld.lld"
AR="llvm-ar"
NM="llvm-nm"
STRIP="llvm-strip"
OBJCOPY="llvm-objcopy"
OBJDUMP="llvm-objdump"
READELF="llvm-readelf"
